# Generated by Django 2.1.7 on 2019-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9000)),
                ('price', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('specification', models.TextField()),
            ],
        ),
    ]
